import type { DemoStep } from '@/types/demo'

const DOCS = 'https://techdocs.broadcom.com/us/en/vmware-tanzu/spring/application-advisor/1-6/app-advisor'

export const howItWorksSteps: DemoStep[] = [
  {
    id: 'how-cli',
    type: 'content',
    section: 'How It Works',
    title: 'Getting the CLI',
    heading: 'One `REGISTRY_TOKEN`, then you\'re running locally',
    body: 'Both CLI forms ship as a single downloadable binary — Linux, Windows, or macOS (Intel or ARM64). Setup is short.',
    bullets: [
      { title: 'Get a token', icon: 'key', description: 'Pull a `REGISTRY_TOKEN` from the Broadcom Support Portal, following the Spring Enterprise Repository guidelines.' },
      { title: 'Download & extract', icon: 'terminal', description: 'Platform-specific `curl`, then `tar -xf advisor-cli.tar --strip-components=1 --exclude=./META-INF`.' },
      { title: 'Optional Maven config', icon: 'file-text', description: 'Only needed for Spring LTS versions or Tanzu extensions — otherwise 1.6\'s embedded recipes need no external Maven repo access at all.' },
    ],
    callout: {
      label: 'Air-gapped by default in 1.6',
      tone: 'success',
      body: 'Commercial recipes are now embedded directly in the CLI binary, so the default upgrade flow works in offline/air-gapped environments with zero external Maven repository access.',
    },
    sourceUrl: `${DOCS}/run-app-advisor-cli.html`,
  },
  {
    id: 'how-diagram-1',
    type: 'diagram',
    section: 'How It Works',
    title: 'Point it at a repo',
    heading: 'Step 1 — everything starts from a Git repository',
    diagramId: 'advisor-upgrade-loop',
    narrative: 'Application Advisor works against a single checked-out repo at a time — a Maven `pom.xml` or Gradle `build.gradle` Spring Boot / Spring Framework project.',
    visibleNodeIds: ['repo', 'cli'],
    visibleEdgeIds: ['e-repo-cli'],
    activeNodeIds: ['cli'],
    sourceUrl: `${DOCS}/upgrade-spring-app.html`,
  },
  {
    id: 'how-diagram-2',
    type: 'diagram',
    section: 'How It Works',
    title: 'SBOM, then a plan',
    heading: 'Step 2 — build a dependency SBOM, then an upgrade plan',
    diagramId: 'advisor-upgrade-loop',
    narrative: '`cf repo build-sbom` resolves the dependency tree (CycloneDX), required JDK, and build-tool version into `.advisor/build-config.json`. `cf repo upgrade-plan` reads that file and prints the ordered steps needed to reach the latest compatible release.',
    visibleNodeIds: ['repo', 'cli', 'sbom', 'plan'],
    visibleEdgeIds: ['e-repo-cli', 'e-cli-sbom', 'e-sbom-plan'],
    activeNodeIds: ['sbom', 'plan'],
    sourceUrl: `${DOCS}/upgrade-spring-app.html`,
  },
  {
    id: 'how-diagram-3',
    type: 'diagram',
    section: 'How It Works',
    title: 'Recipes apply the plan',
    heading: 'Step 3 — OpenRewrite recipes apply changes, one step at a time',
    diagramId: 'advisor-upgrade-loop',
    narrative: '`cf repo apply-upgrade-plan` runs the next step\'s OpenRewrite recipes against your working tree — version bumps *and* Java API rewrites (like `javax` → `jakarta`) — while preserving your code style. You review the diff, test, and commit before applying the next step.',
    visibleNodeIds: ['repo', 'cli', 'sbom', 'plan', 'recipes'],
    visibleEdgeIds: ['e-repo-cli', 'e-cli-sbom', 'e-sbom-plan', 'e-plan-recipes', 'e-recipes-repo'],
    activeNodeIds: ['recipes'],
    sourceUrl: `${DOCS}/upgrade-spring-app.html`,
  },
  {
    id: 'how-diagram-4',
    type: 'diagram',
    section: 'How It Works',
    title: 'Advice, Hub, and CI/CD',
    heading: 'Step 4 — advice, Tanzu Hub, and CI/CD close the loop',
    diagramId: 'advisor-upgrade-loop',
    narrative: 'Beyond version bumps: `cf repo advice` / `apply-advice` recommends Spring Enterprise extensions like `spring-aot`. Publishing the SBOM to Tanzu Hub surfaces support status and vulnerabilities. And in a pipeline, `--push --from-yml` skips the manual loop entirely and opens a pull request.',
    visibleNodeIds: ['repo', 'cli', 'sbom', 'plan', 'recipes', 'advice', 'hub', 'pr'],
    visibleEdgeIds: ['e-repo-cli', 'e-cli-sbom', 'e-sbom-plan', 'e-plan-recipes', 'e-recipes-repo', 'e-recipes-pr', 'e-sbom-hub', 'e-cli-advice'],
    activeNodeIds: ['advice', 'hub', 'pr'],
    sourceUrl: `${DOCS}/integrations.html`,
  },
]
