import type { DemoStep } from '@/types/demo'

const DOCS = 'https://techdocs.broadcom.com/us/en/vmware-tanzu/platform/ai-services/10-4/ai'

export const architectureSteps: DemoStep[] = [
  {
    id: 'arch-overview',
    type: 'content',
    section: 'Architecture',
    title: 'Component inventory',
    heading: 'The pieces on the board',
    body: "Before tracing a request through the system, it's worth naming every component using the exact terms TechDocs uses — these labels show up in Ops Manager, in `cf` output, and in logs.",
    bullets: [
      { title: 'controller', icon: 'server', description: 'BOSH job hosting both the ai-server and genai-broker processes — the unit you scale for HA.' },
      { title: 'ai-server', icon: 'workflow', description: 'The core gateway/proxy — receives inference requests via gorouter and forwards them to model workers.' },
      { title: 'genai-broker', icon: 'git-branch', description: 'The on-demand Cloud Foundry service broker — handles create/bind/delete-service lifecycle for the ai-models marketplace offering.' },
      { title: 'Worker VM', icon: 'boxes', description: 'A dedicated VM per model instance, running nginx (TLS termination) in front of Ollama or vLLM.' },
      { title: 'On/Off-Platform Models', icon: 'cloud', description: 'On-platform = Ollama/vLLM you host; off-platform = OpenAI, Bedrock, Azure OpenAI, Vertex AI, Anthropic proxied through.' },
      { title: 'Plans & Policies', icon: 'layers', description: 'A Plan bundles one or more models behind a marketplace offering; Policies (rate limits, quotas, webhooks) attach to plans.' },
    ],
    sourceUrl: `${DOCS}/reference-architecture.html`,
  },
  {
    id: 'arch-diagram-1',
    type: 'diagram',
    section: 'Architecture',
    title: 'App → routing tier',
    heading: 'Step 1 — a bound app talks to gorouter',
    diagramId: 'system-architecture',
    narrative: "A CF app calls its bound AI Services plan exactly like it would call any other bound service — the request enters through Cloud Foundry's own routing tier, gorouter. Nothing AI-specific happens yet.",
    visibleNodeIds: ['client', 'gorouter'],
    visibleEdgeIds: ['e-client-gorouter'],
    activeNodeIds: ['client', 'gorouter'],
    sourceUrl: `${DOCS}/reference-network-communications.html`,
  },
  {
    id: 'arch-diagram-2',
    type: 'diagram',
    section: 'Architecture',
    title: 'Routing → ai-server',
    heading: 'Step 2 — gorouter forwards to ai-server on port 9092',
    diagramId: 'system-architecture',
    narrative: 'gorouter forwards the inference request to ai-server, the controller job that owns model configuration, plans, policies, audit, and journaling. This is the single gateway every inference call passes through, on-platform or off.',
    visibleNodeIds: ['client', 'gorouter', 'ai-server'],
    visibleEdgeIds: ['e-client-gorouter', 'e-gorouter-aiserver'],
    activeNodeIds: ['ai-server'],
    sourceUrl: `${DOCS}/reference-network-communications.html`,
  },
  {
    id: 'arch-diagram-3',
    type: 'diagram',
    section: 'Architecture',
    title: 'The other controller process',
    heading: 'Step 3 — genai-broker: the marketplace side',
    diagramId: 'system-architecture',
    narrative: "genai-broker lives on the same controller VM as ai-server but handles a completely different job: it's the on-demand CF service broker that answers `cf create-service` / `cf bind-service` / `cf delete-service` calls, on port 10005.",
    visibleNodeIds: ['client', 'gorouter', 'ai-server', 'genai-broker'],
    visibleEdgeIds: ['e-client-gorouter', 'e-gorouter-aiserver', 'e-gorouter-broker'],
    activeNodeIds: ['genai-broker'],
    sourceUrl: `${DOCS}/reference-network-communications.html`,
  },
  {
    id: 'arch-diagram-4',
    type: 'diagram',
    section: 'Architecture',
    title: 'Broker → BOSH',
    heading: 'Step 4 — genai-broker provisions Worker VMs via BOSH',
    diagramId: 'system-architecture',
    narrative: "When a model instance needs to be created or torn down, genai-broker talks to the BOSH director, which owns the actual VM lifecycle. This is why provisioning a new on-platform model takes minutes, not milliseconds — a real VM is being stood up.",
    visibleNodeIds: ['client', 'gorouter', 'ai-server', 'genai-broker', 'bosh'],
    visibleEdgeIds: ['e-client-gorouter', 'e-gorouter-aiserver', 'e-gorouter-broker', 'e-broker-bosh'],
    activeNodeIds: ['bosh'],
    sourceUrl: `${DOCS}/reference-network-communications.html`,
  },
  {
    id: 'arch-diagram-5',
    type: 'diagram',
    section: 'Architecture',
    title: 'Into the Worker VM',
    heading: 'Step 5 — ai-server forwards to nginx, then the model runtime',
    diagramId: 'system-architecture',
    narrative: "Each model instance gets its own dedicated Worker VM — hard resource isolation per model. ai-server forwards to nginx on port 9023 for TLS termination, which hands off to the actual Ollama or vLLM process on port 4000.",
    visibleNodeIds: ['client', 'gorouter', 'ai-server', 'genai-broker', 'bosh', 'worker-nginx', 'worker-runtime'],
    visibleEdgeIds: ['e-client-gorouter', 'e-gorouter-aiserver', 'e-gorouter-broker', 'e-broker-bosh', 'e-aiserver-nginx', 'e-nginx-runtime'],
    activeNodeIds: ['worker-nginx', 'worker-runtime'],
    sourceUrl: `${DOCS}/reference-network-communications.html`,
  },
  {
    id: 'arch-diagram-6',
    type: 'diagram',
    section: 'Architecture',
    title: 'State: config, audit, journal',
    heading: 'Step 6 — PostgreSQL backs configuration, audit, and journaling',
    diagramId: 'system-architecture',
    narrative: 'ai-server persists its configuration, audit trail, and (when enabled) request/response journaling to a backing PostgreSQL database — either broker-provisioned or an external instance you point it at.',
    visibleNodeIds: ['client', 'gorouter', 'ai-server', 'genai-broker', 'bosh', 'worker-nginx', 'worker-runtime', 'postgres'],
    visibleEdgeIds: ['e-client-gorouter', 'e-gorouter-aiserver', 'e-gorouter-broker', 'e-broker-bosh', 'e-aiserver-nginx', 'e-nginx-runtime', 'e-aiserver-postgres'],
    activeNodeIds: ['postgres'],
    sourceUrl: `${DOCS}/how-to-guides-configure-backing-psql.html`,
  },
  {
    id: 'arch-diagram-7',
    type: 'diagram',
    section: 'Architecture',
    title: 'Off-platform proxy path',
    heading: 'Step 7 — the same gateway proxies to the cloud',
    diagramId: 'system-architecture',
    narrative: "The full picture: on-platform inference (through the Worker VM) and off-platform inference (proxied over HTTPS to OpenAI, Bedrock, Azure OpenAI, Vertex AI, or Anthropic) share the exact same ai-server gateway. Developers bind to a plan — they don't need to know or care which side of this diagram actually serves the request.",
    visibleNodeIds: ['client', 'gorouter', 'ai-server', 'genai-broker', 'bosh', 'worker-nginx', 'worker-runtime', 'postgres', 'external'],
    visibleEdgeIds: ['e-client-gorouter', 'e-gorouter-aiserver', 'e-gorouter-broker', 'e-broker-bosh', 'e-aiserver-nginx', 'e-nginx-runtime', 'e-aiserver-postgres', 'e-aiserver-external'],
    activeNodeIds: ['external'],
    sourceUrl: `${DOCS}/reference-architecture.html`,
  },
  {
    id: 'arch-topologies',
    type: 'content',
    section: 'Architecture',
    title: 'Deployment topologies',
    heading: 'Minimal vs. full topology',
    body: "TechDocs lays out two reference topologies depending on how much downtime you can tolerate.",
    bullets: [
      { title: 'Minimal topology', icon: 'boxes', description: 'Single ai-server and genai-broker instance, an optional single non-GPU Ollama model, any backing PostgreSQL. Good for dev/sandbox use — some downtime is acceptable.' },
      { title: 'Full topology', icon: 'layers', description: 'Multiple ai-server and genai-broker instances, multiple model instances across providers (e.g. three Llama 3.1 on T4 GPUs plus two Mistral on A100 GPUs), production-ready PostgreSQL. Downtime must be kept to an absolute minimum.' },
    ],
    callout: {
      label: 'Scaling in practice',
      tone: 'info',
      body: 'Scaling either ai-server or genai-broker is the same operation: Ops Manager → AI Services tile → Resource Config tab → change the instance count on the controller job.',
    },
    sourceUrl: `${DOCS}/reference-deployment-topologies.html`,
  },
]
