import type { DemoStep } from '@/types/demo'

const REPO = 'https://github.com/asaikali/cf-coding-agents/blob/main'
const AI_DOCS = 'https://techdocs.broadcom.com/us/en/vmware-tanzu/platform/ai-services/10-4/ai'
const SECTION = 'How It Works'

export const howItWorksSteps: DemoStep[] = [
  {
    id: 'how-apt-yml',
    type: 'content',
    section: SECTION,
    title: 'What apt.yml adds, and why',
    heading: 'cflinuxfs4 ships a lot for free — this is only the gap',
    body: 'The stack already gives us `git`, `jq`, `build-essential`, `curl`, and the usual diagnostics. None of those show up in `apt.yml`. What does show up is picked for a specific coding-agent reason.',
    bullets: [
      { title: 'temurin-25-jdk', icon: 'cpu', description: "A specific vendor and LTS, not whatever OpenJDK point release Ubuntu's repos happen to carry — added via Adoptium's own apt repo." },
      { title: 'nodejs (NodeSource)', icon: 'workflow', description: "Ubuntu's packaged Node is several majors behind — not viable for the npm/pnpm/vite workflows the agent will trigger." },
      { title: 'gh', icon: 'git-branch', description: 'One well-known CLI for reading issues, opening PRs, and commenting — instead of hand-rolling GitHub\'s REST API from shell.' },
      { title: 'ripgrep', icon: 'terminal', description: 'Agents grep constantly; `rg` is an order of magnitude faster than `grep -r` on a real repo, and it adds up across many invocations.' },
    ],
    callout: {
      label: 'The pattern generalizes',
      tone: 'info',
      body: 'Every one of these is the same three-part declaration in `apt.yml`: a GPG key, a repo line, and a package name. Swap them and you\'re pulling in Corretto instead of Temurin, or any other vendor that publishes a Debian repo.',
    },
    sourceUrl: `${REPO}/01-claude-cli/README.md`,
  },
  {
    id: 'how-diagram-build-1',
    type: 'diagram',
    section: SECTION,
    title: 'Staging the droplet',
    heading: 'Step 1 — apt-buildpack runs ahead of the release buildpack',
    diagramId: 'agent-droplet-build',
    narrative: '`cf push --task` chains two buildpacks: `apt-buildpack` first, `binary_buildpack` last. Only the *last* buildpack in the chain owns the release/start contract — apt-buildpack\'s job ends at "everything in apt.yml is installed."',
    visibleNodeIds: ['payload', 'apt-buildpack'],
    visibleEdgeIds: ['e-payload-apt'],
    activeNodeIds: ['apt-buildpack'],
    sourceUrl: `${REPO}/README.md`,
  },
  {
    id: 'how-diagram-build-2',
    type: 'diagram',
    section: SECTION,
    title: 'A stopped, task-only droplet',
    heading: 'Step 2 — staged once, run any number of times',
    diagramId: 'agent-droplet-build',
    narrative: 'The manifest declares zero `web` instances and a `task` process. `cf push --task` leaves the droplet staged and stopped; every `cf run-task` afterward is a fresh, isolated invocation against the same droplet.',
    visibleNodeIds: ['payload', 'apt-buildpack', 'droplet', 'task'],
    visibleEdgeIds: ['e-payload-apt', 'e-apt-droplet', 'e-droplet-task'],
    activeNodeIds: ['droplet', 'task'],
    sourceUrl: `${REPO}/01-claude-cli/manifest.yaml`,
  },
  {
    id: 'how-credentials',
    type: 'content',
    section: SECTION,
    title: 'Credentials without touching the manifest',
    heading: 'Two user-provided services, never a manifest secret',
    body: 'Every scenario needs an Anthropic API key and a GitHub token. Neither is baked into the droplet or lives in a tracked file — each is handed to CF once, outside of any push, as its own user-provided service.',
    bullets: [
      { title: 'anthropic-creds', icon: 'key', description: '`cf create-user-provided-service anthropic-creds -p \'{"api_key":"..."}\'` — bound in the manifest, never on a push command line.' },
      { title: 'github-creds', icon: 'key', description: 'Same shape, `token` field — used by both `gh` and, once wired, plain `git` over HTTPS.' },
      { title: 'Rotate without a re-push', icon: 'sparkles', description: '`cf update-user-provided-service <name> -p <json>` — the very next task invocation reads the fresh value.' },
    ],
    callout: {
      label: 'Two services, not one',
      tone: 'info',
      body: 'Separate UPS per credential so each can rotate and be shared with other apps independently, rather than one combined secret blob.',
    },
    sourceUrl: `${REPO}/README.md#how-credentials-reach-the-agent`,
  },
  {
    id: 'how-diagram-creds-1',
    type: 'diagram',
    section: SECTION,
    title: 'One blob in, VCAP_SERVICES',
    heading: 'Step 1 — CF hands the container one JSON blob',
    diagramId: 'agent-credential-flow',
    narrative: 'CF injects a single env var, `VCAP_SERVICES`, whose value is JSON describing every bound service and its credentials — not the flat `ANTHROPIC_API_KEY` / `GH_TOKEN` the tools actually expect.',
    visibleNodeIds: ['ups', 'vcap'],
    visibleEdgeIds: ['e-ups-vcap'],
    activeNodeIds: ['vcap'],
    sourceUrl: `${REPO}/01-claude-cli/agent/.profile.d/vcap.sh`,
  },
  {
    id: 'how-diagram-creds-2',
    type: 'diagram',
    section: SECTION,
    title: 'Bridged by .profile.d/vcap.sh',
    heading: 'Step 2 — parsed and re-exported before every task',
    diagramId: 'agent-credential-flow',
    narrative: 'Any `*.sh` in `.profile.d/` is sourced by CF\'s launcher before any start command — including every ad-hoc `cf run-task`. `vcap.sh` pulls both secrets out with `jq`, exports them flat, and wires `gh` as git\'s HTTPS credential helper so a plain `git push` uses the same token.',
    visibleNodeIds: ['ups', 'vcap', 'profile', 'tools'],
    visibleEdgeIds: ['e-ups-vcap', 'e-vcap-profile', 'e-profile-tools'],
    activeNodeIds: ['profile', 'tools'],
    sourceUrl: `${REPO}/01-claude-cli/agent/.profile.d/vcap.sh`,
  },
  {
    id: 'how-swap-intro',
    type: 'content',
    section: SECTION,
    title: 'The trick: same binary, different model',
    heading: 'ANTHROPIC_BASE_URL is just an environment variable',
    body: 'The Claude Code CLI reads `ANTHROPIC_BASE_URL`, `ANTHROPIC_MODEL`, and `ANTHROPIC_API_KEY` from its environment on every invocation. Nothing about the droplet, the skill file, or the prompt has to change to point it somewhere else — only what `cf run-task --command` sets before `./bin/claude` runs.',
    bullets: [
      { title: 'ANTHROPIC_BASE_URL', icon: 'globe', description: 'Swap `api.anthropic.com` for a Tanzu AI Services endpoint that speaks the identical Messages API wire format.' },
      { title: 'ANTHROPIC_MODEL', icon: 'bot', description: 'Name the on-platform model — `qwen3.6-27b` — instead of a Claude model id.' },
      { title: 'ANTHROPIC_API_KEY', icon: 'key', description: 'A service-key pulled from the platform, not an Anthropic org key.' },
    ],
    callout: {
      label: 'This is the same feature from the AI Services demo',
      tone: 'success',
      body: 'The Anthropic-wireformat plan is exactly the "Anthropic Messages API" gateway feature covered in the Tanzu AI Services demo — `anthropic-qwen3.6` is just one more plan on the same `ai-models` marketplace offering, reachable through the same one gateway.',
    },
    sourceUrl: `${AI_DOCS}/how-to-guides-create-a-plan-using-the-anthropic-api.html`,
  },
  {
    id: 'how-diagram-swap-1',
    type: 'diagram',
    section: SECTION,
    title: 'The default path',
    heading: 'Step 1 — unmodified, the binary talks to real Anthropic',
    diagramId: 'agent-model-swap',
    narrative: 'With no overrides, `./bin/claude` behaves exactly like it would on a laptop: it calls `api.anthropic.com` using whatever `ANTHROPIC_API_KEY` is present.',
    visibleNodeIds: ['binary', 'anthropic'],
    visibleEdgeIds: ['e-binary-anthropic'],
    activeNodeIds: ['binary'],
    sourceUrl: `${REPO}/01-claude-cli/run.sh`,
  },
  {
    id: 'how-diagram-swap-2',
    type: 'diagram',
    section: SECTION,
    title: 'The swap',
    heading: 'Step 2 — three env vars later, it talks to on-platform Qwen',
    diagramId: 'agent-model-swap',
    narrative: 'Override `ANTHROPIC_BASE_URL`, `ANTHROPIC_MODEL`, and `ANTHROPIC_API_KEY` at `cf run-task` time with values pulled from the `anthropic-qwen-model` service key, and the identical binary, skill, and prompt now drive Qwen 3.6 27B running on-platform — no rebuild, no redeploy, no code change.',
    visibleNodeIds: ['binary', 'anthropic', 'ai-services', 'qwen'],
    visibleEdgeIds: ['e-binary-anthropic', 'e-binary-aiservices', 'e-aiservices-qwen'],
    activeNodeIds: ['ai-services', 'qwen'],
    sourceUrl: `${AI_DOCS}/how-to-guides-create-a-plan-using-the-anthropic-api.html`,
  },
]
