import {
  Activity,
  BarChart3,
  Bot,
  Boxes,
  Braces,
  Cloud,
  Cpu,
  Database,
  FileText,
  Gauge,
  GitBranch,
  Globe,
  HelpCircle,
  KeyRound,
  Layers,
  Lock,
  MessageSquare,
  Network,
  PlayCircle,
  Route,
  Rocket,
  Server,
  Shield,
  ShieldCheck,
  Sparkles,
  Terminal,
  Users,
  Waypoints,
  Workflow,
  type LucideProps,
} from 'lucide-react'

export const iconRegistry = {
  activity: Activity,
  'bar-chart': BarChart3,
  bot: Bot,
  boxes: Boxes,
  braces: Braces,
  cloud: Cloud,
  cpu: Cpu,
  database: Database,
  'file-text': FileText,
  gauge: Gauge,
  'git-branch': GitBranch,
  globe: Globe,
  'help-circle': HelpCircle,
  key: KeyRound,
  layers: Layers,
  lock: Lock,
  message: MessageSquare,
  network: Network,
  play: PlayCircle,
  route: Route,
  rocket: Rocket,
  server: Server,
  shield: Shield,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  terminal: Terminal,
  users: Users,
  waypoints: Waypoints,
  workflow: Workflow,
} as const

export type IconName = keyof typeof iconRegistry

export function Icon({ name, ...props }: { name: string } & LucideProps) {
  const Component = iconRegistry[name as IconName] ?? Sparkles
  return <Component {...props} />
}
